FROM ubuntu:14.04
MAINTAINER mail@andreasbaumann.cc

RUN apt-get update -y
RUN apt-get install -y wget cmake make gcc fuse-devel mysql-devel unzip gcc-c++

RUN wget -O TEST.zip https://github.com/skeyby/mysqlfs/archive/TEST.zip

RUN unzip TEST.zip && cd mysqlfs-TEST && cmake . && make && make install
ENTRYPOINT ["/usr/local/bin/mysqlfs"]
